export const CARS=[
  {
    id:"0",
    brand:"Mercedes-Benz",
    model:"CLS W218",
    year:"2016",
    mileage:"67 200 km",
    price:"174 990 PLN",
    fuel:"Benzin",
    image1:'car1/main',
    image2:'car1/side1',
    image3:'car1/side2',
    power:"408 KM",
    displacement:"4 663 cm3",
    cylinders: "8",
    color:"Black",
    gearBox:"Automatic",
    gears: "7",
    driveChain:"4x4"
  },
  {
    id:"1",
    brand:"Mercedes-Benz",
    model:"CLS W219",
    year:"2007",
    mileage:"199 217 km",
    price:"39 999 PLN",
    fuel:"Benzin",
    image1:'car2/main',
    image2:"car2/side1",
    image3:"car2/side2",
    power:"388 KM",
    displacement:"5 461 cm3",
    cylinders: "8",
    color:"Black",
    gearBox:"Automatic",
    gears: "7",
    driveChain:"Rear"
  
  },
  {
    id:"2",
    brand:"Opel",
    model:"Astra GTC",
    year:"2005",
    mileage:"257 811 km",
    price:"11 999 PLN",
    fuel:"Benzin/LPG",
    image1:'car3/main',
    image2:"car3/side1",
    image3:"car3/side2",
    power:"125 KM",
    displacement:"1796 cc",
    cylinders: "4",
    color:"Panacotta",
    gearBox:"Manual",
    gears: "5",
    driveChain:"Front"
  },
  {
    id:"3",
    brand:"BMW",
    model:"M3 F80",
    year:"2015",
    mileage:"50 300 km",
    price:"175 000 PLN",
    fuel:"Benzin",
    image1:'car4/main',
    image2:"car4/side1",
    image3:"car4/side2",
    power:"479 KM",
    displacement:"2 979 cm3",
    cylinders: "6",
    color:"White",
    gearBox:"Automatic",
    gears: "7",
    driveChain:"Rear"
  },
  {
    id:"4",
    brand:"Kia",
    model:"Stinger",
    year:"2019",
    mileage:"500 km",
    price:"210 900 PLN",
    fuel:"Benzin",
    image1:'car5/main',
    image2:"car5/side1",
    image3:"car5/side2",
    power:"366 KM",
    displacement:"3 342 cm3",
    cylinders: "6",
    color:"White",
    gearBox:"Automatic",
    gears: "8",
    driveChain:"Rear"

  },
  {
    id:"5",
    brand:"BMW",
    model:"7 Series",
    year:"2018",
    mileage:"16 500 km",
    price:"399 999 PLN",
    fuel:"Diesel",
    image1:'car6/main',
    image2:"car6/side1",
    image3:"car6/side2",
    power:"400 KM",
    displacement:"2 993 cm3",
    cylinders: "6",
    color:"Black",
    gearBox:"Automatic",
    gears: "8",
    driveChain:"4x4"

  },
  {
    id:"6",
    brand:"Lexus",
    model:"LS",
    year:"2017",
    mileage:"59 900 km",
    price:"399 999 PLN",
    fuel:"Hybrid",
    image1:'car7/main',
    image2:"car7/side1",
    image3:"car7/side2",
    power:"300 KM",
    displacement:"3 456 cm3",
    cylinders: "6",
    color:"Black",
    gearBox:"Automatic",
    gears: "8",
    driveChain:"4x4"

  },
  {
    id:"7",
    brand:"Audi",
    model:"RS7",
    year:"2016",
    mileage:"19 900 km",
    price:"399 999 PLN",
    fuel:"Benzin",
    image1:'car8/main',
    image2:"car8/side1",
    image3:"car8/side2",
    power:"605 KM",
    displacement:"3 993 cm3",
    cylinders: "8",
    color:"Blue",
    gearBox:"Automatic",
    gears: "8",
    driveChain:"4x4"

  },
];